trigger:
- main  # or any branch name in the repo you want to trigger from

stages:
- stage: Build
  displayName: Build Docker Image
  jobs:
  - job: DockerBuild
    displayName: Build Dockerfile from Public GitHub Repo
    pool:
      name: default

    steps:
    - checkout: none  # don't checkout the default repo

    - script: |
        git clone https://github.com/tdonaldson231/csharp-automation-framework-playwright.git
      displayName: 'Clone public GitHub repo'

    - task: Docker@2
      displayName: 'Build Docker image'
      inputs:
        command: build
        dockerfile: $(Build.SourcesDirectory)/csharp-automation-framework-playwright/Dockerfile
        buildContext: $(Build.SourcesDirectory)/csharp-automation-framework-playwright
        repository: myimage
        tags: |
          $(Build.BuildId)