trigger: none  # No automatic trigger; you’ll run this manually or customize as needed

parameters:
- name: gitRepoUrl
  displayName: 'GitHub Repo URL'
  type: string
  default: 'https://github.com/tdonaldson231/csharp-automation-framework-playwright.git'

- name: gitBranch
  displayName: 'GitHub Branch to Clone'
  type: string
  default: 'main'

stages:
- stage: Build
  displayName: Build Docker Image
  jobs:
  - job: DockerBuild
    displayName: Build Dockerfile from Parametrized GitHub Repo
    pool:
      name: default

    steps:
    - checkout: none  # Skip default repo checkout

    - script: |
        if exist csharp-automation-framework-playwright (
          echo Deleting existing directory...
          rmdir /s /q csharp-automation-framework-playwright
        )
        git clone -b ${{ parameters.gitBranch }} ${{ parameters.gitRepoUrl }}
      displayName: 'Clean and Clone GitHub Repo Branch'

    - task: Docker@2
      displayName: 'Build Docker image'
      inputs:
        command: build
        dockerfile: $(Build.SourcesDirectory)/csharp-automation-framework-playwright/Dockerfile
        buildContext: $(Build.SourcesDirectory)/csharp-automation-framework-playwright
        repository: myimage
        tags: |
          $(Build.BuildId)
