services:
  integration:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      - MYSQL_SERVER=${MYSQL_SERVER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./Config/Sql/mysql-init:/docker-entrypoint-initdb.d
    networks:
      - shared-test-network

volumes:
  mysql-data:

networks:
  shared-test-network:
    external: true
