#version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: test-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # change this
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d  # loading SQL scripts on startup

volumes:
  mysql-data:
