name: Build and Run .NET Tests

on:
  workflow_dispatch:
    inputs:
      test_env:
        description: "Test Environment"
        required: false
        default: "dev"
      test_category:
        description: "Test Category"
        required: false
        default: "smoke"

env:
  #GIT_REPO: "https://github.com/tdonaldson231/csharp-automation-framework-playwright.git"
  IMAGE_NAME: "test-image"
  IMAGE_TAG: "latest"

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        # with:
        #   repository: tdonaldson231/csharp-automation-framework-playwright
        #   ref: main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Start MySQL with Docker Compose
        run: |
          docker compose -f Config/Sql/docker-compose.yml up -d
          docker compose -f Config/Sql/docker-compose.yml ps

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Run Tests
        run: |
          mkdir -p test-results
          docker run --rm \
            --network sql_test-network \
            -e TEST_ENV=${{ github.event.inputs.test_env }} \
            -e TEST_CATEGORY=${{ github.event.inputs.test_category }} \
            -v ${{ github.workspace }}/test-results:/app/TestResults \
            $IMAGE_NAME:$IMAGE_TAG