name: Build and Run .NET Tests

on:
  workflow_dispatch:
    inputs:
      test_env:
        description: "Test Environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - integration

      test_category:
        description: "Test Category"
        required: true
        default: "smoke"
        type: choice
        options:
          - smoke
          - regression
          - journeys
          - integration

env:
  IMAGE_NAME: "test-image"
  IMAGE_TAG: "latest"

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Start MySQL with Docker Compose
        run: |
          docker compose -f Config/Sql/docker-compose.yml up -d
          docker compose -f Config/Sql/docker-compose.yml ps

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Run Tests
        run: |
          mkdir -p test-results
          docker run --rm \
            --network sql_test-network \
            -e TEST_ENV=${{ github.event.inputs.test_env }} \
            -e TEST_CATEGORY=${{ github.event.inputs.test_category }} \
            -v ${{ github.workspace }}/test-results:/app/TestResults \
            $IMAGE_NAME:$IMAGE_TAG

      - name: Publish .trx Results
        uses: dorny/test-reporter@v1
        if: always()  # Show results even if tests fail
        with:
          name: .NET Test Results
          path: '**/test-results.trx'  # Adjust if your file is elsewhere
          reporter: dotnet-trx

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: TestReport
          path: Reports/ExtentReport_*.html.html