name: Build and Run .NET Tests

on:
  workflow_dispatch:
     inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - integration

      testCategory:
        description: 'Test category to run'
        required: true
        default: 'smoke'
        type: choice
        options:
          - smoke
          - regression
          - api
          - journeys

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'  # Adjust as needed

    - name: Run Tests with TRX Output
      run: |
        dotnet test AutomationFrameworkRepo_v03.sln \
          --logger "trx;LogFileName=test_results.trx" \
          --settings "Tests/RunSettings/${{ github.event.inputs.environment }}.runsettings" \
          --filter "TestCategory=${{ github.event.inputs.testCategory }}"
